[package]
name = "cicero-dsl"
version = "0.1.0"
description = "Compiler for the Cicero DSL to create interactive document templates"
homepage.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]

[lints]
workspace = true
