[package]
name = "cicero-dsl"
version = "0.1.0"
description = "Web-app for working with the Cicero DSL."
homepage.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]

[lints]
workspace = true
