unstable_features = true

condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = false # 'true' goes crazy for some reason (reorders alphabetically, then by trait order, then again..)
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
