//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::categories::Entity as Categories;
pub use super::templates::Entity as Templates;
pub use super::templates_categories::Entity as TemplatesCategories;
pub use super::users::Entity as Users;
pub use super::users_visible_templates::Entity as UsersVisibleTemplates;
