version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sleep infinity
    networks:
      - db
      - mailer
    volumes:
      - ..:/workspace/cicero:cached
    env_file:
      - .env
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  mailer:
    image: mailtutan/mailtutan:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - mailer
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace/cicero:cached
    env_file:
      - .env


volumes:
  postgres-data:

networks:
  db:
  mailer:
