name: Primary pipeline
on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format workspace with rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --all --check

  clippy:
    name: Lint workspace with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy --all-targets --all-features -- -D warnings

  check:
    name: Check workspace for compile-ability
    runs-on: ubuntu-latest
    needs: [ fmt, clippy ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo check
        run: cargo check --workspace --all-features --all-targets

  test:
    name: Test workspace
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace --all-features --all-targets

#  build:
#    runs-on: ubuntu-latest
#    name: Build leptos
#    needs: [ test ]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: dtolnay/rust-toolchain@nightly
#        with:
#          targets: "wasm32-unknown-unknown"
#      - uses: Swatinem/rust-cache@v2
#      - uses: jetli/trunk-action@v0.4.0
#      - name: Build
#        run: |
#          cargo build --verbose
#          rustup target add wasm32-unknown-unknown
#          trunk build